In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [13]:
df = pd.read_csv("../data/3_train.csv")
df

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1
0,60,30,19.890000,47.596667,19.200000,44.790000,19.79,44.730000,19.000000,45.566667,...,48.900000,17.033333,45.530000,6.600000,733.500000,92.000000,7.000000,63.000000,5.30,13.275433
1,60,30,19.890000,46.693333,19.200000,44.722500,19.79,44.790000,19.000000,45.992500,...,48.863333,17.066667,45.560000,6.483333,733.600000,92.000000,6.666667,59.166667,5.20,18.606195
2,50,30,19.890000,46.300000,19.200000,44.626667,19.79,44.933333,18.926667,45.890000,...,48.730000,17.000000,45.500000,6.366667,733.700000,92.000000,6.333333,55.333333,5.10,28.642668
3,50,40,19.890000,46.066667,19.200000,44.590000,19.79,45.000000,18.890000,45.723333,...,48.590000,17.000000,45.400000,6.250000,733.800000,92.000000,6.000000,51.500000,5.00,45.410389
4,60,40,19.890000,46.333333,19.200000,44.530000,19.79,45.000000,18.890000,45.530000,...,48.590000,17.000000,45.400000,6.133333,733.900000,92.000000,5.666667,47.666667,4.90,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,110,0,23.426667,35.656667,21.533333,35.326667,22.79,35.090000,21.600000,36.230000,...,36.723333,19.600000,36.700000,13.366667,765.500000,39.666667,4.000000,40.000000,-0.05,4.642817
15996,120,0,23.356667,35.466667,21.500000,35.200000,22.79,35.090000,21.600000,35.930000,...,37.245000,19.600000,36.626667,13.300000,765.500000,40.000000,4.000000,40.000000,0.00,4.617919
15997,120,10,23.290000,35.326667,21.500000,35.060000,22.79,35.030000,21.533333,35.656667,...,37.730000,19.633333,36.360000,13.166667,765.516667,40.833333,3.833333,40.000000,0.15,19.006672
15998,100,0,23.260000,35.060000,21.426667,34.800000,22.79,35.000000,21.500000,35.363333,...,37.790000,19.633333,36.433333,13.033333,765.533333,41.666667,3.666667,40.000000,0.30,1.851090
15999,170,0,23.175000,34.820000,21.356667,34.526667,22.79,35.000000,21.500000,35.156667,...,37.400000,19.600000,36.333333,12.900000,765.550000,42.500000,3.500000,40.000000,0.45,29.504855

In [14]:
df = df.dropna()
X = df.drop(["rv1"], axis=1)
y = df["rv1"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [16]:
tree = DecisionTreeRegressor()
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)

In [17]:
print("mse", mean_squared_error(y_test, y_pred))
print("mae", mean_absolute_error(y_test, y_pred))

mse 425.77924729372916
mae 16.79449210731036